sounds:
  enabled: true
  on-reward: "minecraft:entity.item.pickup"
  on-confirm: "minecraft:entity.item.pickup"

command:
  Confirmer:
    - 'givemysterybox %player% epic_box'
    - 'tell %player% Your confirmation has been received, You have been rewarded!'
  Inviter:
    - 'givemysterybox %player% epic_box'
    - 'tell %player% %Confirmer% has confirmed your invitation. You have been rewarded! Invites: %invites% Position: %position%'