name: AdvancedInvite
version: '1.1-SNAPSHOT'
main: skyxnetwork.advancedInvite.AdvancedInvite
api-version: '1.20'
commands:
  invite:
    description: Invite un ami sur le serveur
    usage: /invite <pseudo>
  confirm:
    description: Confirme une invitation reçue
    usage: /confirm <pseudo>